// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHO1avEonyRiVYu7nFPnqAoJSo6udPTPk',
    appId: '1:82515951865:web:0441af077e356bc9466228',
    messagingSenderId: '82515951865',
    projectId: 'flutterbookingapp-6a729',
    authDomain: 'flutterbookingapp-6a729.firebaseapp.com',
    storageBucket: 'flutterbookingapp-6a729.appspot.com',
    measurementId: 'G-HW9Y1BE05N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2YC9IW9oJJ8dCppqMvdo-9wFPdzwkJtY',
    appId: '1:82515951865:android:b582bfb08aac6172466228',
    messagingSenderId: '82515951865',
    projectId: 'flutterbookingapp-6a729',
    storageBucket: 'flutterbookingapp-6a729.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARQ2rpehqaxUXDoo87OPjxnwVecc7KhGg',
    appId: '1:82515951865:ios:61b9f2112f113ed3466228',
    messagingSenderId: '82515951865',
    projectId: 'flutterbookingapp-6a729',
    storageBucket: 'flutterbookingapp-6a729.appspot.com',
    androidClientId: '82515951865-iblt1ln8ru3dniv89rika8mm03ttbivu.apps.googleusercontent.com',
    iosClientId: '82515951865-jmpck1tnudhvardiqg0e2o6teeostape.apps.googleusercontent.com',
    iosBundleId: 'edmt.dev.flutterBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARQ2rpehqaxUXDoo87OPjxnwVecc7KhGg',
    appId: '1:82515951865:ios:61b9f2112f113ed3466228',
    messagingSenderId: '82515951865',
    projectId: 'flutterbookingapp-6a729',
    storageBucket: 'flutterbookingapp-6a729.appspot.com',
    androidClientId: '82515951865-iblt1ln8ru3dniv89rika8mm03ttbivu.apps.googleusercontent.com',
    iosClientId: '82515951865-jmpck1tnudhvardiqg0e2o6teeostape.apps.googleusercontent.com',
    iosBundleId: 'edmt.dev.flutterBookingApp',
  );
}
